### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by zhangpur** [agrimgupta92/sgan#1]
I am confused with getting preprocessed data from original UCY dataset (zara01,zara02,univ), as there only gives annotations in image coordinate system. Can you provide data preprocessing code? Thanks very much!

**Comment by agrimgupta92** [comment]
We used approximations to calculate the homography matrix for e.g. using the dimensions of a car (of specific model/company) and then using the homography matrix to convert from pixel to real world coordinates. At this time the code for data is not publicly available and I can't provide a timeline as to when that will happen.

**Comment by avijit9** [comment]
How did you plot trajectories on images then (Fig. 6 in the paper)? If possible, can you make the code online for plotting trajectories?

**Comment by agrimgupta92** [comment]
You might find this https://github.com/agrimgupta92/sgan/issues/5#issuecomment-414381686 helpful.

**Comment by trungmanhhuynh** [comment]
@avijit9 Are you able to plot the correct trajectories ?
