### ISSUE TITLE
Non-linearity of the trajectory

### ISSUE THREAD

**Issue by zhangpur** [agrimgupta92/sgan#10]
Hi, Agrim,
Have you used the value <non_linear_ped> to measure the results on nonlinear trajectories? I could not find relative part in the evaluate code.

Thanks for help!

**Comment by agrimgupta92** [comment]
Yes I did use that for debugging and various experimental things I tried. I left it in the data loader as I thought people might find it useful. However, I have removed evaluation etc for the same during code cleanup.

**Comment by zhangpur** [comment]
Thanks for reply. 
Another question: 
I saw you have made coordinates relative in trajectory preprocessing, which is used in all the rnn models during training. Things you produce are relative coordinates too.  The absolute coordinates are only used in pooling mechanism.  Am I getting it right?

**Comment by agrimgupta92** [comment]
Absolute coordinates are not used in pooling. In pooling we use absolute coordinates to find out relative positions of all people in a scene w.r.t to the person for which we are calculating the pooling vector.

**Comment by zhangpur** [comment]
Thanks. I think I should express more clearly.
The coordinates used in encoder of the Generator are <obs_traj_rel>:
final_encoder_h = self.encoder(obs_traj_rel)
in decoder of the generator are <last_pos_rel>:
decoder_input = self.spatial_embedding(last_pos_rel) 

Variable  <xx_rel> means the relative coordinates between time steps(spirit of velocity). Have you tried use the absolute coordinates to train the GAN network?

**Comment by agrimgupta92** [comment]
I have tried using absolute coordinates to train the GAN. However, I found it extremely hard to train anything meaningful with absolute coordinates.

**Comment by zhangpur** [comment]
Thanks, it helps a lot! Actually, I'm using absolute coordinates in my current work. Maybe the absolute trajectory needs to be somewhat normalized
