### ISSUE TITLE
Question: How to get predicted trajectory?

### ISSUE THREAD

**Issue by daehoumich** [agrimgupta92/sgan#13]
Hi,

Is there any simple way to save the predicted trajectory (e.g., x-y coordinates) in a txt or any file format?

**Comment by agrimgupta92** [comment]
No we don't provide any utility function to do that. You can dump it in the same format as the input txt file.

**Comment by James-ml** [comment]
Have you solved this problem?I also want to get this result.Thx. @daehoumich
