### ISSUE TITLE
Question: Training error

### ISSUE THREAD

**Issue by daehoumich** [agrimgupta92/sgan#14]
When I run the training commend: python scripts/train.py

I got an error message:

ValueError: could not convert string to float: '0.0\t1.0\t1.41\t-5.68'
Any idea that can help me to fix it? 

(When I run 'run_traj.sh', the training runs well).

Many thanks in advance.

**Comment by agrimgupta92** [comment]
Refer delim option in https://github.com/agrimgupta92/sgan/blob/master/TRAINING.md#dataset-options. For you the delim should be '\t'.

**Comment by daehoumich** [comment]
It worked! Thank you so much.

Here is one more error:
Traceback (most recent call last):
  File "scripts/train.py", line 580, in <module>
    main(args)
  File "scripts/train.py", line 148, in main
    batch_norm=args.batch_norm)
  File "/home/daeho/sgan-master/sgan/models.py", line 425, in __init__
    if self.noise_dim[0] == 0:

Should I change noise_dim?

**Comment by mingbocui** [comment]
Hi,

I have the same problem with "ValueError: could not convert string to float: '0.0\t1.0\t1.41\t-5.68'". It is weird that this error still exists even if I have added " --delim '\t' "(also tried with --delim='\t'). Do you have any suggestions? Many thanks!

Warm regards

**Comment by Fangyh09** [comment]
@mingbocui --delim "tab" works for me.
