### ISSUE TITLE
Please Help!: How to save pred_traj_fake tensor?

### ISSUE THREAD

**Issue by daehoumich** [agrimgupta92/sgan#17]
Hi, 

Could anyone can help me to save the 'pred_traj_fake (final prediction of this model)' tensor as the format compatible to be used in Matlab? 

I am not an expert on python and torch so I am struggling at saving this variable. I would like to use it for some visualization. 

Thanks in advance~!

**Comment by daehoumich** [comment]
I converted it to numpy array and export it as matlab file using scipy.io.savemat. Is it right direction?

**Comment by agrimgupta92** [comment]
Yes, you can also refer https://stackoverflow.com/questions/10997254/converting-numpy-arrays-to-matlab-and-vice-versa.

**Comment by James-ml** [comment]
Have you solved this problem?I also want to get this result.Thx.
