### ISSUE TITLE
Hyper-parameters

### ISSUE THREAD

**Issue by zhangpur** [agrimgupta92/sgan#20]
Hi, Gupta,
The suggested dimension of hidden states in the paper are 16 and 32 for encoder and decoder. The default parameters in the code are 64 and 128. Is that mean 16 and 32 are a better value for training?  I'm also wondering about the  dimension of hidden states of the baseline method(LSTM and Social LSTM) used in your paper. Can you give a help?

**Comment by agrimgupta92** [comment]
For hyper parameters you should look at the print_args script and not the default values. The hidden states for LSTM and Social LSTM should be the same as the ones used for Social GAN and you can get them from print_args.
