### ISSUE TITLE
Varying length trajectories

### ISSUE THREAD

**Issue by jagjeet-singh** [agrimgupta92/sgan#21]
I noticed that the trajectories with length less than desired sequence length are filtered out in `trajectories.py`. Is it possible to make it work for varying trajectory lengths, with lengths being anything between 1 to seq_len?

**Comment by agrimgupta92** [comment]
You can remove the filtering and pad the sequence with zeros. The only caveat with this approach is that in some sense you are asking the model to predict at what time step the person started to walk.

**Comment by jagjeet-singh** [comment]
Thank you for the reply. On the same lines, isn't it better to also consider the frame? If a pedestrian was present from frame #5 to #15. We can pad the frames 1-4 with the position at #5 and frames 16-20 with the position at #15. The intuition is that the pedestrian must have entered the scene at #5 and left the scene at #15. This might be better than padding with zeros and encountering huge jumps.
As long as the first frame of pedestrian is before frame #8, the model need not have to predict when the pedestrian started walking.

**Comment by agrimgupta92** [comment]
See the updated comment. I meant relative coordinates.

**Comment by agrimgupta92** [comment]
Let us assume that seq_len is 5. We have a trajectory which is [0, 0, 0, 5, 6] (this is only the x-coordinate). Now, if we pad with initial position we will have [5, 5, 5, 5, 6]. The corresponding relative coordinates will be [0, 0, 0, 0, 1]. I meant this when I said pad with zeros in the relative coordinates. Sorry for the confusion but I think we both are on the same page. 
Now, two cases are possible. Consider if this was part of observed sequence. As opposed to other trajectories the model does not have sufficient context to predict the future. 
If the observed sequence was instead [0, 0, 0, 0, 0] and prediction was [0, 0, 0, 5, 6]. Then you are asking the model to basically predict when the person started walking (or entered the frame).

**Comment by jagjeet-singh** [comment]
Thank you! That was really helpful. I'm training Social-GAN on an autonomous driving dataset and it would be a bad idea to ignore partial trajectories there. I've done zero padding as you suggested and started training.

**Comment by w00zie** [comment]
@jagjeet-singh I'm trying to expand Social-GAN into an automotive context, using the KITTI dataset. Do you have any suggestion based on your work? Thank you.

**Comment by RebornHugo** [comment]
Can we simply set `min_ped=len(peds_in_curr_seq)` to ensure that no neighbors are filtered?
