### ISSUE TITLE
Implementation of S-LSTM

### ISSUE THREAD

**Issue by trungmanhhuynh** [agrimgupta92/sgan#31]
Hi @agrimgupta92, Are you able to share with me your implementation of S-LSTM and LSTM model, that 
produced the results in your paper ? 

That's help a lot.
Thanks for your great work.

**Comment by w00zie** [comment]
I'm interested in these models as well.

Thanks.

**Comment by agrimgupta92** [comment]
Unfortunately I don't have access to those models anymore. However, the core implement of social pooling module can be found [here](https://github.com/agrimgupta92/sgan/blob/master/sgan/models.py#L233). It should be straightforward to develop on top if this.
