### ISSUE TITLE
Question: Error with shape 

### ISSUE THREAD

**Issue by saranshvora** [agrimgupta92/sgan#32]
Hi, 

I am evaluating eth pretrained model with my own dataset. I run into this: 

` curr_seq[_idx, :, pad_front:pad_end] = curr_ped_seq
ValueError: could not broadcast input array from shape (2,44) into shape (2,16)`

error. I am not able to understand if I have to change any parameters or not while testing with my own data. Can you please help me out ?

**Comment by atanas1054** [comment]
I am having the same problem. Any ideas?

**Comment by saranshvora** [comment]
yes, I solved it. The dataset that you are using may be has more number of sequences than desired by trajectories.py 
`                    if pad_end - pad_front != self.seq_len:
                        continue`

this part causes the error. So just check how many points does each pedestrian has. You'll need it less than the sequence length.  And also check for the similar repeated points of each pedestrian(x,y). The dataset used has different for each frame. After you solve this you may have errors if you solve them let me know.

**Comment by atanas1054** [comment]
Got it. Thank you.
