### ISSUE TITLE
Usages of loss_mask, linear_ped, Non_linear_ped in the code

### ISSUE THREAD

**Issue by ybpaopao** [agrimgupta92/sgan#38]
Hi,  there are some variables like loss_mask, linear_ped, non_linear_ped but I do not know their usages. I did not find them in your work of sgan. So, what your purpose of using these variables? For example, you calculated disp_error, disp_error_l, and disp_error_nl, what's the difference?

**Comment by agrimgupta92** [comment]
I used these variables for tracking different methods, models I tried over the course of the project. Non linear trajectories are harder to model/predict and can give indication if some method is able to better model these non-linear trajectories.
