### ISSUE TITLE
Why I could not get the same result with the paper? 

### ISSUE THREAD

**Issue by mingbocui** [agrimgupta92/sgan#41]
I just run evaluate_model.py with the trained model provided by the author, but the error of ADE and FDE are both much bigger than the results displayed in the paper. Is there anything else I have to take care when running the evaluate_model.py?

**Comment by HorryChen** [comment]
Hello, I just started to contact the related research on pedestrian trajectory prediction. This is the first time that I contacted this project such as SGAN. I met some difficulties and doubts in my study. Would you like to give me your email address? Thank you. And my email address is wisionpeng@163.com. I'm looking forward to your reply. Sincerely Wision Peng

**Comment by amiryanj** [comment]
We have also explored a new trajectory prediction architecture, called **Social-Ways**. We will present this work at CVPR workshop. The paper will be released soon (on arxiv and CVF), and I would be interested to see your feedbacks.
javad.amirian@inria.fr

**Comment by amiryanj** [comment]
The mentioned paper is now available on arxiv:
https://arxiv.org/abs/1904.09507

We will start to publish the source codes, ASAP.

**Comment by onlylove321** [comment]
Hello, I'd like to ask if there is anything to change in this code. Why is the result of my operation so bad as that of my paper?@amiryanj

**Comment by onlylove321** [comment]
Can you reproduce the experimental results in this paper? I have problems with the results of my operation, and the gap is very large.@amiryanj

**Comment by amiryanj** [comment]
I just used the pre-trained models and the results are quite the same as in the paper.
@onlylove321

**Comment by mingbocui** [comment]
@amiryanj have you tried just used the hyperparameters provided by the scripts and train the model by yourself? I have got different results, hope for your insights.

**Comment by amiryanj** [comment]
Hi @mingbocui 
I'm afraid that I've never get that prediction accuracies by training, always thinking I'm doing something wrong.
I just know that the `l2_loss_weight` is set to zero while it should be something, otherwise you may let such GAN run for few days to get converged.

**Comment by ybpaopao** [comment]
Hi, @mingbocui, have you found any method that can solve the problem you mentioned? I also trained SGAN with different hyperparameters but the results are far away from the paper.
