### ISSUE TITLE
Unable to get decent performances upon training the model

### ISSUE THREAD

**Issue by AyeshaNirma** [agrimgupta92/sgan#6]
Hi Agrim,

I have used default parameters to train on zara01 as described in read me. The errors are horrendous so for pred len : 8 and 12 the ADE is 2.27 and 9.02 respectively. Its a but puzzling as I have done absolutely no changes to your code or model whatsoever and I have used all default params. Could you perhaps point out what potentially could be the issue.

**Comment by agrimgupta92** [comment]
When you say default parameters there are 3 possibilities: 
1. Default params in the train script
2. Params in run_traj.sh script 
3. Params from running print args on one of the pre-trained models. 
I would trust 2,3 more. Training GANs in my experience was really tough and the hyper-parameters in 2,3 worked well for me. I would suggest looking at weight init.
