### ISSUE TITLE
Version of cuda and cudnn

### ISSUE THREAD

**Issue by YouAndMe8342** [agrimgupta92/sgan#76]
Dear fellows, when I was running train.py, I encountered an error, whose last line is showed as follows:

RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:143

I searched this problem from several pages, learning that it may be caused by the difference between the versions of cuda and cudnn from the author's and mine. I tried the combinations of cuda 9.2 & cudnn 7.1, as well as cuda 9.0 & cudnn 7.1. Unfortunately both were in vain. So could you please tell me the correct environment to correctly run this project?(including all the versions of cuda, cudnn, etc.)?

My CONFIGURATION: torch==0.4.0, torchvision==0.2.0, GTX1650(Notebooks), python3.6, Ubuntu18.04.

This problem was extremely torturing...
Thanks a lot in advance!!!

**Comment by Jhfyut** [comment]
hi,How did you solve the problem
